apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    version: blue    # Initially routing to the blue version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
