
apiVersion: apps/v1
kind: StatefulSet 
metadata: 
       name: stateful
       labels:
            app: stateful
spec: 
    replicas: 4  #how many replica's you want to create on the basis of template
    template:
      metadata:  #like a tag
         name: stateful
         labels: 
            app:  stateful
      spec:
        containers:
            - name: mypod-stateful-cont
              image: mysql:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: dbport
                  containerPort: 3306
                  protocol: TCP
              env:
                 - name: MYSQL_ROOT_PASSWD
                   value: "1234"
    selector:
        matchLabels:
          app: stateful
