apiVersion:  v1  
kind: Pod
metadata:  
     labels:
       name: mypod4
       app: mypod4
spec:
 containers:
    - name: mypod-nginx
      image: nginx:latest
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---
      apiVersion: v1 
      kind: Service
      metadata:
              name: podlb  
      spec:
          selector:
                app: mypod4 
          type: LoadBalancer 
          ports:
          - protocol: TCP
            port: 80
            targetPort: 80
            name: nginx