apiVersion: v1  
kind: Pod
metadata:  
      name: mypod4
      labels:
       app: mypod4
spec:
 containers:
    - name: mypod-nginx
      image: nginx:latest
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
          
---

      apiVersion: v1 
      kind: Service
      metadata:
              name: podlb  
      spec:
          type: LoadBalancer 
          selector:
              app: mypod4 
          ports:
          - protocol: TCP
            port: 80
            targetPort: 80
            name: nginx