apiVersion: v1  
kind: Pod
metadata:  
      name: mypod3
      labels:
        app: mypod3

spec:
 containers:
    - name: mypod-cont3
      image: nginx:latest
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---

      apiVersion: v1 
      kind: Service
      metadata:
              name: podnodeport 
      spec:
          selector:
                app: mypod3 
          type: NodePort 
          ports:
          - protocol: TCP
            port: 80
            targetPort: 80
            name: nginx