apiVersion: v1
kind: Pod
metadata:
        name: mypod1
spec:
      container:
        -name: mypod-cont1
        image:  nginx:latest
        resources
            requests:
                cpu: "50m"
                memory: "100Mi"
        ports:
            -name: http
            containerPort: 80
            protocol tcp: TCP
