apiVersion: v1
kind: Service
metadata:
    name: clusterip

spec:
    type: ClusterIP
    selector:
      app:  mypod1
    ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
      name: nginx
      
      