apiVersion: apps/v1
kind: Deployment
metadata:
    name: student-microservice
spec:
   replicas: 2
  selector:
    matchLabels:
       app: student-microservice
template:
    metadata:
    labels:
    app: student-microservice
spec:
     containers:
    - name: student-microservice
     image: <your-registry>/student-microservice:latest
ports:
     - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: student-microservice-service
spec:
  selector:
    app: student-microservice
ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
 type: ClusterIP
