apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers: # corrected from 'container' to 'containers'
        - name: studentapp
          image: shruti786/student
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: studentapp-service
spec:
  selector:
    app: studentapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
