apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-deployment
  labels:
    app: my-app
    version: a
spec:
  replicas: 3   # Number of replicas for stable version
  selector:
    matchLabels:
      app: my-app
      version: a
  template:
    metadata:
      labels:
        app: my-app
        version: a
    spec:
      containers:
      - name: my-app
        image: nginx:latest  # Stable version image
        ports:
        - containerPort: 80
